### ISSUE TITLE
Any idea why Overwatch is "Pro"?

### ISSUE THREAD

**Issue by Legomaniac** [dafzor/bnetlauncher#1]
Just wondering if you had any insight to this. I can't seem to find anything by Googling. It's the only battlenet URI launch key that seems out of place.

**Comment by dafzor** [comment]
Only blizzard can give you a definitive answer, but my guess it's after Prometheus, which I assume was Overwatch codename during development.

**Comment by Legomaniac** [comment]
Thanks for the reply! I am assuming that is the case. Now that I have Googled "blizzard prometheus" there are many mentions to it being the code name for Overwatch. I was surprised however that there were no mentions of this in the Wikipedia article. Perhaps I can update it. :)
