### ISSUE TITLE
Battle.net Beta client - URL scheme shortcuts not working

### ISSUE THREAD

**Issue by Kopert** [dafzor/bnetlauncher#13]
Hello,

Most URLs to launch games are not working on the current Battle.net Beta client. I don't know if this is a temporary issue or if the correct URLs have changed.

Here's the list that I have tested:

- battlenet://WoW - not working
- battlenet://D3 - not working
- battlenet://WTCG - not working
- battlenet://Pro - not working
- battlenet://S2 - not working (but battlenet://starcraft works to start Starcraft 2)
- battlenet://Hero - not working (but battlenet://heroes works to start HotS)
- battlenet://SCR - not working
- battlenet://DST2 - can't test

I realize that the Battle.net Beta client is in Beta for a reason and maybe it's a problem on their end, but I figured I'd open an issue to let you know and keep this in mind.

Also, I don't know how to find these URLs other than trial-and-error. If there's a better way to find these, I'd love to know.

**Comment by reed216** [comment]
Hello,
This seems to be a issue with the Beta Clients themselves. It appears that the new client converts the Handle URI's in to lowercase when passing them it to the game controller. Since all family UID's are case sensitive the game controller fails to find a matching family UID meaning no nothing is launched.

This is the Stable clients behavior 
```
D 2017-10-14 03:35:10.379337 [CommandQueue] {Main} Received IPC Message: IPC_COMMAND
I 2017-10-14 03:35:10.379358 [CommandQueue] {Main} Dispatching Command: handle_uri battlenet://S2/
I 2017-10-14 03:35:10.379375 [ScreenController] {Main} Changing screen to: Games
D 2017-10-14 03:35:10.379448 [GameController] {Main} Selecting game family by id: S2
D 2017-10-14 03:35:10.379460 [GameController] {Main} Active family set to: S2
D 2017-10-14 03:35:10.417011 [GameController] {Main} Active product set to: S2_starter
```
This is the Beta clients behavior
```
D 2017-10-14 03:42:11.422142 [CommandQueue] {Main} Received IPC Message: IPC_COMMAND
I 2017-10-14 03:42:11.422207 [CommandQueue] {Main} Dispatching Command: handle_uri battlenet://S2/
I 2017-10-14 03:42:11.422233 [ScreenController] {Main} Changing screen to: Games
D 2017-10-14 03:42:11.422293 [GameController] {Main} Selecting game family by id: s2
```

There is no family UID named "s2" so the client does nothing.
There's nothing that can be done until this is fixed.

**Comment by Kopert** [comment]
Right, I thought it would probably be an issue with their Beta, so I also started a thread on their beta feedback forums to report this issue. Here's hoping they realize this and fix it so we can keep using the functionality without changing our setups.

Meanwhile, I'm extracting the executable paths to replace my personal shortcuts (for example, in my case, `battlenet://WTCG` can be replaced with `"C:\Program Files (x86)\Hearthstone\Hearthstone.exe" -launch -uid hs_beta` with the same effect, i.e., launches the game skipping the BNet client but still using auth data). If push comes to shove and this remains unfixed we could always go this route for the shortcuts. If you need this information for the other games just let me know.

**Comment by reed216** [comment]
That method unfortunately doesn't work for all games. WoW will log you in then instantly disconnect you requiring you to log back in and if I recall correctly Overwatch used to have issues where it would default back to US servers frequently. 

Hopefully the issue will be fixed.

**Comment by Kopert** [comment]
Yeah, you're right; further testing showed me that some games don't work too well (couldn't get WoW to work at all). I'll let you know if I get any answer from Blizzard on the issue.

**Comment by dafzor** [comment]
Thanks for doing all the investigation into the issue @iMintty, I didn't even knew battle.net had debug logs.

Has for a fix, easy solution is blizzard being nice and fixing it, hopefully it wasn't an intencional change to break bnetlauncher or similar solutions and get more eyes on their launcher.

 For now I'll wait hoping it gets sorted, but if it's permanent change I have a few ideas on workarounds but I'm unsure if they'd work.

Leaving a link here to remind myself to check blizzard response if any: https://us.battle.net/forums/en/bnet/topic/20759169203

**Comment by Kopert** [comment]
Seems to be fixed on the latest Battle.net update.

**Comment by dafzor** [comment]
Can confirm, glad this one closed :).
