### ISSUE TITLE
Make bnetlauncher controller config compatible

### ISSUE THREAD

**Issue by JoshWobbles** [dafzor/bnetlauncher#20]
I know this has been brought up elsewhere, but i wonder if changing the Process.Start() method to a blocking command, think its Process.WaitForExit() or somthing like that, it may keep bnetlauncher active and allow for any controller profile assigned within steam to remain active instead of switching back to the desktop configuration.

**Comment by dafzor** [comment]
What game are you having trouble with? I just tested Overwatch and it still works, as long as the steam overlay remains attached the steam controller should work as expected.

**Comment by JoshWobbles** [comment]
Destiny 2

**Comment by dafzor** [comment]
Destiny 2 already has a [special case](https://github.com/dafzor/bnetlauncher/blob/master/bnetlauncher/Program.cs#L316) that does just what you've mentioned so it shows as still playing.

For SteamController support though I recommend [GloSC](https://alia5.github.io/GloSC/) which is a much better tool, if you scroll down the comments on issue #10 there's step by step instructions of how other users made it work for them.

**Comment by JoshWobbles** [comment]
I am using a XBox controller, not a steam controller, I just want steam to recognize the game and switch profiles, which it does not. Please re-open so it can be considered down the road.

**Comment by dafzor** [comment]
But I assume you're using your xbox controller trough Steam Input correct? So it's the same as a Steam Controller.

I can take a look into having bnetlauncher trigger the Steam Input profile, but [GloSC](https://alia5.github.io/GloSC/) will still be a better solution since it's focused on your particular use case.
