### ISSUE TITLE
Configurable timeout?

### ISSUE THREAD

**Issue by eai04191** [dafzor/bnetlauncher#24]
Hello. bnetlauncher is wonderful, but with my PC, bnetlauncher took about 45 seconds to start the game from Battlenet.
In other words, bnetlauncher times out and can not find the game.
Perhaps, this problem will not be common.
However, I would be happy if I could specify the timeout time on the command line.

**Comment by dafzor** [comment]
I'm sorry to hear that, I'll see what I can do.

**Comment by dafzor** [comment]
If you're willing to try an early "beta" you can download [this build](https://madalien.com/pub/bnetlauncher/bnetlauncher_v199b.zip) that adds the -t <time in seconds> launch option to see if it works for you.

Do note however that this version is a major rework of the program so some things might be broken.

**Comment by eai04191** [comment]
Yay! It perfectly worked for me! Thanks! 😆

**Comment by dafzor** [comment]
Version 2.00 is out which has the timeout option so closing this bug.
