### ISSUE TITLE
Enhancement: Allow manual opening of games

### ISSUE THREAD

**Issue by scarrken** [dafzor/bnetlauncher#25]
What I mean by that is: if you don't input any shortcuts (ow, wow etc.) it will just open battle.net and whatever game is manually selected afterwards.
I know this is possible from a bug, actually. Older versions of bnetlauncher would let you do this unintentionally. This is useful (at least from what I can use) to open Overwatch PTR through steam, letting me fully use the steam controller without fiddling with other programs.

Though I use the hacky way to do it (just using an old version)

**Comment by dafzor** [comment]
I suppose it would be one way to support ptr. And in the [current beta](https://madalien.com/pub/bnetlauncher/bnetlauncher_v199b3.zip) it's actually fairly straight forward to do.

You need is to create a gamesdb.ini file with the following config:

	[owptr]
	name=Overwatch PTR
	client=battlenet
	exe=Overwatch.exe
	options=nolaunch

and place it next to bnetlauncher.exe or in `%localappdata%\madalien.com\bnetlauncher` folder. Then use owptr as the launch option.

**Comment by scarrken** [comment]
Oh that's actually a neat solution
