### ISSUE TITLE
Always exits Blizzard client

### ISSUE THREAD

**Issue by ReplicaObscura** [dafzor/bnetlauncher#3]
I'm running into an issue where, every time I launch Overwatch through bnetlauncher, even though Battle.net is already running in the background, it exits after I quit the game. However, it does not do this if I launch the game without bnetlauncher.

Looking at the code, it seems it's only supposed to exit the client if it wasn't already started, so I'm not positive what could be happening. Has anyone else seen this behavior?

**Comment by dafzor** [comment]
Could you also provide a log (instructions on the included readme), I'll try to take a look at the issue during the weekend.

**Comment by dafzor** [comment]
Should be fixed now, please download and try release 1.10 you can find it on the usual spot http://madalien.com/stuff/bnetlauncher/ or simply compile the latest source.

**Comment by ReplicaObscura** [comment]
Wow, thanks for the quick response! I'll give it a try right away.

**Comment by ReplicaObscura** [comment]
Just tested and it's working great! Thanks again.
