### ISSUE TITLE
Warcraft 3 reforged support

### ISSUE THREAD

**Issue by Ethan-BB** [dafzor/bnetlauncher#30]
Good day,

Battle.net client now supports launching of Warcraft 3: Reforged via
`--exec="launch W3"` argument.
Requesting an addition into default gamedb.

It also looks like, it should be possible to launch WC3 classic via this after patch 1.30.2 on December 1st.
[- Source one](https://us.forums.blizzard.com/en/warcraft3/t/pre-purchase-access-to-classic/1243)[ and two](https://us.forums.blizzard.com/en/warcraft3/t/pre-purchase-access-to-classic/1243/14)

**Comment by dafzor** [comment]
Do you know the name of the game exe file?

**Comment by Ethan-BB** [comment]
There’s no exe yet. Same situation as when they added CoD. It currently only opens battle.net client on Warcraft 3 tab.

**Comment by dafzor** [comment]
Well already did a commit guessing it would keep the same exe as the original game, hopefully it will work.

**Comment by reed216** [comment]
The game exe is listed as "Warcraft III.exe" at [us.patch.battle.net:1119/w3/blob/game](url)

**Comment by dafzor** [comment]
Release v2.02 is up with the changed exe so closing the issue, if it doesn't work i'll reopen it.
