### ISSUE TITLE
Call of Duty: Modern Warfare

### ISSUE THREAD

**Issue by Ethan-BB** [dafzor/bnetlauncher#34]
Good morning,

new year, new CoD game added to Battle.net
launch argument looks something like this:

`Q:\Games\Battle.net\Battle.net.exe  --exec="launch ODIN"`

However I have still no idea what executable name they'll use.
Also, if I may, I'd like to suggest launch argument to be `bnetlauncher.exe codmw2019` as we have no idea how more stupid naming scheme they'll use in future.

**Comment by dafzor** [comment]
Already pushed the [changes](https://github.com/dafzor/bnetlauncher/commit/ee9abbae3ae7825add442131162ff39d8ae4d45c), will do the release once the real exe name is known.

**Comment by dafzor** [comment]
Fixed in release v2.06
