### ISSUE TITLE
BUG - Mutes All Sound Devices When Using To Launch Any Game

### ISSUE THREAD

**Issue by ghost** [dafzor/bnetlauncher#39]
So I tried this app and it works great, the only problem is it mutes all sound on my pc and then I can't enjoy the game because I can't hear anything. My setup is on window10 I use a Bluetooth speaker and headset for sound, neither work. After launching a game with the bnetlauncher I am presented with my game with all system sounds muted. Upon closing the game all system sounds return to normal.

**Comment by dafzor** [comment]
bnetlauncher has no interaction with windows sound sub system. Maybe you've configured the games/bnetlauncher to output to a different audio device ingame and/or windows controls?

**Comment by CaseygWoelfle** [comment]
Nope they are set to default audio source. It's not just the game either.
It's my entire pc and all sounds from anywhere. Even chrome for instance
gets muted when using your app.

**Comment by CaseygWoelfle** [comment]
It might also be worth mentioning that my audio is all Bluetooth.

**Comment by ghost** [comment]
> bnetlauncher has no interaction with windows sound sub system. Maybe you've configured the games/bnetlauncher to output to a different audio device ingame and/or windows controls?

I looked in to this further, turns out it wasn't your app. I am sorry. I went and tested all my bnet games without using your launcher and still had no sound. A repair of all my games fixed the issues.

**Comment by dafzor** [comment]
Glad you got it fixed.
