### ISSUE TITLE
bnetlauncher crash

### ISSUE THREAD

**Issue by joebywan** [dafzor/bnetlauncher#4]
Setup in steam, D3 for the shortcut launch options.

Immediately crashes, Diablo 3 doesn't launch.

Log file attached.

[debug_20170522_1608328301.log.txt](https://github.com/dafzor/bnetlauncher/files/1017882/debug_20170522_1608328301.log.txt)

The errors thrown in the event viewer:

[dotNetRuntime.txt](https://github.com/dafzor/bnetlauncher/files/1017900/dotNetRuntime.txt)

[Application Error.txt](https://github.com/dafzor/bnetlauncher/files/1017886/Application.Error.txt)

Any other info I can provide to help out?

**Comment by dafzor** [comment]
Sorry for the late reply, does Diablo 3 start normally without bnetlauncher?

**Comment by joebywan** [comment]
Yep it does

**Comment by dafzor** [comment]
Could you try opening the windows run dialog (shortcut Winkey+R) and running battlenet://D3 
![run_d3](https://cloud.githubusercontent.com/assets/1612206/26352383/70ec17a0-3fb3-11e7-807a-6ec3fc3faaa3.png)

Does that work?

**Comment by joebywan** [comment]
I tried that and it didn't load it.  So I'm assuming the associations were screwed somehow.  I checked the default programs and nothing was showing up as an option to assign to the battlenet protocol.

I'm reinstalling the app and I'll let you know if it comes good.

**Comment by joebywan** [comment]
Reinstalled, it seems to have fixed the protocol association, and now it's working.  Thanks for the assistance :)

**Comment by dafzor** [comment]
No problem.

**Comment by dafzor** [comment]
Added additional checks to the latest version so hopefully if it happens to other people it should give a more informative error.
