### ISSUE TITLE
-nolaunch Doesn't Seem to Work

### ISSUE THREAD

**Issue by orchrist-pc** [dafzor/bnetlauncher#40]
I have multiple WoW accounts and am trying to set this up to give me a moment to switch between accounts prior to launch. When I run the following, the game will launch right after the client opens. I've also tried modifying the gamesdb.ini to add the option in there and I'm getting the same result.

bnetlauncher.exe wowclassic -nolaunch

**Comment by dafzor** [comment]
The nolaunch option is actually not supported as a command line option.

Only way to use is trough gamedb.ini by adding the following entry which adds the option to the internal gamedb:
```ini
[wowclassic]
options=nolaunch
```

**Comment by orchrist-pc** [comment]
Ah, I see what happened. My ini was named "gamesdb.ini" rather than "gamedb.ini".

**Comment by dafzor** [comment]
I see i mistakenly named the example file gamesdb.ini. Latest version will look for both gamesdb.ini and gamedb.ini.

Sorry for the confusion.
