### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by SilverSaw** [dafzor/bnetlauncher#42]
Hi there,

Thanks a lot for this great software. Some of the issues in wow are related to cache, can i delete somehow cache foulder before opening your launcher ?

Usually before i was using .bat for this purpose - attached code, now i am unable to use it because we are not opening your launcher with regular target path and there must be wowclassic at the end:
```
rmdir /s /q "E:\World of Warcraft\_classic_\Cache"
START "" "E:\World of Warcraft\_classic_\Wow.exe"
```

Best Regards

**Comment by dafzor** [comment]
Just add your cmd.exe as steam non game and `/c "path to your bat file"` as parameter.

Example bat file:
```batch
echo "hello world"
start /wait d:\games\steam\bnetlauncher.exe ow
```

If you don't want to see the console window you can try using [one of these programs](https://www.raymond.cc/blog/hidden-start-runs-batch-files-silently-without-flickering-console/) to keep it hidden.

**Comment by SilverSaw** [comment]
Thanks for the help, in my case it is working as intended like this:
```
rmdir /s /q "E:\World of Warcraft\_classic_\Cache"
start /wait E:\Launchers\Battle.net\bnetlauncher_v208\bnetlauncher.exe wowclassic
```
PS: Also used Hidden Start (HStart) to remove CMD window as your proposal.

Best Regards.
