### ISSUE TITLE
Codmw2019 command prompt

### ISSUE THREAD

**Issue by zoppablue** [dafzor/bnetlauncher#44]
When I open up cod, it loads up correctly and fast. But the command prompt does not go away until I close the game.

This does not happen with ow or wow.

**Comment by dafzor** [comment]
Bnetlauncher only shows a command window if compiled in debug mode. The normal release should show no Windows.

As for staying open it's intended since Steam wont show you as playing if bnetlauncher isn't running, so it waits for the game to exit.
