### ISSUE TITLE
CoD MW2: CR

### ISSUE THREAD

**Issue by MaximusX800** [dafzor/bnetlauncher#45]
I'm not seeing, in the Read Me documentation for v2.09, that Call of Duty: Modern Warfare 2 Campaign Remastered is supported.

Will this be added at some point?

**Comment by dafzor** [comment]
I would need to know the launcher id for it. It can be obtained from the file `C:\ProgramData\Battle.net\Agent\product.db` (hidden file) of a system with the game installed.

I don't know if that file has any sensible data, so please just open it in a text editor and screenshot the relevant bit has I've done for diablo 3 bellow.

![image](https://user-images.githubusercontent.com/1612206/93920106-a0586480-fd06-11ea-9754-d5c6e3f06b3f.png)

**Comment by MaximusX800** [comment]
I reviewed the information provided, but the does not exist.  And yes, I do have the game installed at this time.

**Comment by dafzor** [comment]
Did you not find the reference of the game in the file or didn't find the file at all?

**Comment by MaximusX800** [comment]
The file does not exist, under the directory provided.  I also searched for it, and could not find it.

**Comment by dafzor** [comment]
It's a hidden file, it wont show on searches or explorer unless you enable "show hidden files"

![image](https://user-images.githubusercontent.com/1612206/93947482-b6304e80-fd33-11ea-88b2-4af74f4f1bbc.png)

**Comment by MaximusX800** [comment]
Here is a screenshot of the requested information.

[https://imgur.com/v3paJn8](url)

**Comment by dafzor** [comment]
Ok, just need one last thing which is the name of the game exe. After that I'll post a test version.

**Comment by MaximusX800** [comment]
Two .exes in install dir:

MW2 Campaign Remastered Launcher.exe
MW2CR.exe

Not really sure what the launcher exe is for, there is no launcher loaded before the game loads, but I think most CoD games have them.

**Comment by dafzor** [comment]
Give the new [v2.10b1](https://github.com/dafzor/bnetlauncher/releases/tag/v2.10b1) beta release a try.

**Comment by MaximusX800** [comment]
Thank you, I'll test this out and report back.

The build notes reminded me of something else, I'll create a new issue if you see it as an option, but example game Tetris Effect via Epic game store, there doesn't seem to be away to launch it in VR mode with out the Epic client.  Thoughts?

**Comment by dafzor** [comment]
I've only tested the epic support with some of the "free" titles, namely GTA V, Dauntless and World War Z.

You can try adding the game to the beta version of bnetlauncher using the "custom game" instructions. You can find the needed code by creating a game desktop shortcut and looking at the properties.
![image](https://user-images.githubusercontent.com/1612206/94090562-d03e5f80-fe0d-11ea-968b-53a9c4b261e3.png)

**Comment by dafzor** [comment]
Released with 2.11
