### ISSUE TITLE
WoW Shadowlands and Classic can not enter

### ISSUE THREAD

**Issue by SilverSaw** [dafzor/bnetlauncher#49]
Hi,

Updating my main post with latest findings.

Last 1 year i am playing only wow classic using bnetlauncher_v208 without any issues and WoW Shadowlands pre-patch with bnetlauncher_v208 without any issues. After Shadowlands release few days ago i am experiencing following issues. 

1.When i use bnetlauncher_v211 to open WoW Classic after loading of bnetlauncher it is instantly giving me error showed on this picture https://ibb.co/1qP7GHt , then it is giving me game not found error https://ibb.co/6tZKJBP
2. When i use bnetlauncher_v211 to open WoW Shadowlands it is giving me game not found error showed on this video. https://youtu.be/wxbw6X05J7s
3. When i use bnetlauncher_v208 to open WoW Classic it is working as intended
4. When i use bnetlauncher_v208 to open WoW Shadowlands it is same behvior as point 2 showing game not found error https://ibb.co/6tZKJBP

If the bnet launcher is loaded minimized in system tray before i start bnetlauncher_v211
5. When i use bnetlauncher_v211 to open WoW Classic it is giving me same errors like in point 1.
6. When i use bnetlauncher_v211 to open WoW Shadowlands it is working, but not closing bnetlauncher, minimizing it in system tray.
If the bnet launcher is loaded minimized in system tray before i start bnetlauncher_v208
7. When i use bnetlauncher_v208 to open WoW Classic it is working, but not closing bnetlauncher, minimizing it in system tray.
8. When i use bnetlauncher_v208 to open WoW Shadowlandsit is working, but not closing bnetlauncher, minimizing it in system tray.

For now i can use your launcher only if i preload bnet launcher on windows startup and stay on background which is unnecessary recourse lock. Also if i play only WoW Classic i can use bnetlauncher_v208.

**Comment by dafzor** [comment]
I've done some testing and couldn't reproduce the problem. Does everything work normally when using Battle.net client only?

**Comment by SilverSaw** [comment]
Please check this video https://youtu.be/wxbw6X05J7s

**Comment by SilverSaw** [comment]
Also to add that if my bnet launcher is already open in system tray. Game is opening as intended from your launcher, this is happening only if bnet launcher is not open at all.

**Comment by SilverSaw** [comment]
More bugs found i am summarizing all of the information. Also updating my main post.

For now i were playing only wow classic using bnetlauncher_v208 without any issues and WoW Shadowlands pre-patch with bnetlauncher_v208 without any issues. After Shadowlands release few days ago i am experiencing following issues.

1.When i use bnetlauncher_v211 to open WoW Classic after loading of bnetlauncher  it is instantly giving me error showed on this picture https://ibb.co/1qP7GHt , then it is giving me game not found error https://ibb.co/6tZKJBP
2. When i use bnetlauncher_v211 to open WoW Shadowlands it is giving me game not found error showed on this video. https://youtu.be/wxbw6X05J7s
3. When i use bnetlauncher_v208 to open WoW Classic it is working as intended
4. When i use bnetlauncher_v208 to open WoW Shadowlands it is same behvior as point 2 showing game not found error https://ibb.co/6tZKJBP

If the bnet launcher is loaded minimized in system tray before i start bnetlauncher_v211
5. When i use bnetlauncher_v211 to open WoW Classic it is giving me same errors like in point 1.
6. When i use bnetlauncher_v211 to open WoW Shadowlands it is working, but not closing bnetlauncher, minimizing it in system tray.
If the bnet launcher is loaded minimized in system tray before i start bnetlauncher_v208
7. When i use bnetlauncher_v208 to open WoW Classic it is working, but not closing bnetlauncher, minimizing it in system tray.
8. When i use bnetlauncher_v208 to open WoW Shadowlandsit is working, but not closing bnetlauncher, minimizing it in system tray.

For now i can use your launcher only if i preload bnet launcher on windows startup and stay on background which is unnecessary recourse lock. Also if i play only WoW Classic i can use bnetlauncher_v208.

**Comment by dafzor** [comment]
Thanks for the detailed report, once I saw your video I realized I was still using the beta Battle.net client.

Could you test this version and see if it fixes the issue?
[bnetlauncher_v212b1.zip](https://github.com/dafzor/bnetlauncher/files/5610530/bnetlauncher_v212b1.zip)

**Comment by SilverSaw** [comment]
Just tried bnetlauncher_v212b1.zip same issues as v211

**Comment by dafzor** [comment]
First beta should fix the not launching issue, after some more digging I believe to have also resolved the WoW Classic launch crash.

[bnetlauncher_v212b2.zip](https://github.com/dafzor/bnetlauncher/files/5610652/bnetlauncher_v212b2.zip)

**Comment by SilverSaw** [comment]
bnetlauncher_v212b2.zip working as intended, tested for both wowshadowlands and wowclassic !

Thanks for the fast response and keep the good work !

Best Regards.
