### ISSUE TITLE
Release EXE files on GitHub

### ISSUE THREAD

**Issue by ElPumpo** [dafzor/bnetlauncher#5]

**Comment by dafzor** [comment]
Any reason why this would be "better" then just getting them of the page http://madalien.com/stuff/bnetlauncher/ ?

**Comment by ShizCalev** [comment]
You can get email alerts from git about them.

**Comment by dafzor** [comment]
I've already been tagging releases on github as I release binaries on the website so you can get the notifications already. I know it might be more convenient but at the moment I have no plans to include the binary package in the release page.

**Comment by ElPumpo** [comment]
It's much easier to track versions via github..? it will only take you seconds to upload them here...
