### ISSUE TITLE
cold war issue

### ISSUE THREAD

**Issue by LargePepsiBottle** [dafzor/bnetlauncher#51]
cant seem to launch cold war using this '"C:\Users\Andrew\Downloads\bnetlauncher_v213\bnetlauncher.exe" codbocw -t 10' is how i have it set up right now whenever i launch the game the overlay doesnt activate

**Comment by dafzor** [comment]
[Cold War afaik does not support the steam overlay](https://www.reddit.com/r/blackopscoldwar/comments/jumgi8/has_anyone_successfully_added_the_steam_overlay/), all bnetlauncher will do is show you as playing it on steam.
