### ISSUE TITLE
WoW Classic not launching

### ISSUE THREAD

**Issue by vaindil** [dafzor/bnetlauncher#53]
Hello, thank you for this awesome tool! I'm on the new, updated version of Battle.net (1.33.0.12769), bnetlauncher 2.13, and WoW Classic does not launch when I use the `wowclassic` tag. It opens the launcher and switches the dropdown to WoW Classic, but it doesn't actually click the Play button, I get the standard "Couldn't find World of Warcraft Classic running" error message. Retail works just fine, Overwatch works fine, but WoW Classic doesn't.

**Comment by dafzor** [comment]
duplicate of #37.
