### ISSUE TITLE
CoD: MW 2019 not launching properly

### ISSUE THREAD

**Issue by joaostavares** [dafzor/bnetlauncher#58]
After the season 3 update, the executable apparently starts the game, even showing playing on the battlenet launcher, but seconds later without actually opening the game, it terminates the process without starting.
I tried to run with timeout but without success.
All other games work normally.
I collected the logs but I don't know if it was a change in the game, or in the battlenet.

[debug_20210720.log](https://github.com/dafzor/bnetlauncher/files/6845439/debug_20210720.log)

**Comment by dafzor** [comment]
Can't exactly recall if MW 2019 was one of them but other CoD games have disabled steam overlay as anti cheat measures.

So my first guess would be game closing when it detects steam overlay, does the game still exit if you use bnetlauncher only without steam?

It could also be battle.net client setting environment variables for the game that it needs or the game needed the battle.net client to be it's parent process which would require a considerable rework on how bnetlauncher starts games.

You can also see if the  `--notask` and `--leaveopen` switches (with a closed battle.net client) change anything.

**Comment by joaostavares** [comment]
I tried to run it directly using a desktop shortcut and now it ran, probably the problem is the game's anti-cheat.
Sorry to take your time with something you can't solve.
