### ISSUE TITLE
Add support for SoM version of Classic WOW

### ISSUE THREAD

**Issue by SilverSaw** [dafzor/bnetlauncher#68]
Hello,

Regarding issue #37 and my research for the main issue in #56, there is workaround i worked with until SoM came out. Basically i made .bat file where it opens battle.net for part of the second on my screen, then wait a bit and use your launcher to open game. Main issue was that if battle.net launcher is minimized or not visible on main screen you launcher is not opening ClassicWoW, but only giving error. 

Now when SoM is released your launcher is automatically launching Classic TBC by default, could you please integrate and Classic SoM version of the game so i can still use it.

If youre interested in the workaround maybe it could be implemented as a function in your launcher. It must show battle.net just for part of the second on the screen and then your launcher works.
`@echo off
start E:\Launchers\Battle.net\Battle.net\Battle.net.exe
TIMEOUT 4
start /D "E:\World of Warcraft" Wow.exe`

Where Wow.exe is your launcher.

Best Regards.

**Comment by dafzor** [comment]
The possible causes have already been discussed in #37 that said if you wanted to add a delay you could do so in [around this line](https://github.com/dafzor/bnetlauncher/blob/cca7f9b4edd49650977bee0969639c8056010415/bnetlauncher/Clients/BnetClient2.cs#L78).

I've updated the README.md to clarify I'm no longer working on this project which is why there hasn't been a fix.

**Comment by dafzor** [comment]
Forgot to mention you may also want to check [LaunchPad](https://github.com/VolantisDev/Launchpad) has an alternative.

**Comment by SilverSaw** [comment]
I am not talking about issue with delay i am talking about new wow classic servers called SoM. We need this option like every other game in Battlenet. Now with wowclassic in the shortcut it is opening classic tbc by default. Can you add this new game to the list pls ?

**Comment by dafzor** [comment]
Wasn't aware there was a new WoW edition, and yes, if given the correct code I can add it to the [gamedb.ini](https://github.com/dafzor/bnetlauncher/blob/master/bnetlauncher/Resources/gamesdb.ini)

**Comment by SilverSaw** [comment]
I am not aware where to find correct "cmd=" for wowclassic som, but i will continue to search. Can you give me some hints, where did people get this info usually?
