### ISSUE TITLE
Add support for Classic World of Warcraft

### ISSUE THREAD

**Issue by SilverSaw** [dafzor/bnetlauncher#70]
![Capture1](https://user-images.githubusercontent.com/1420683/148372161-bb537c4a-40b0-4f0f-a3db-47a52de5a1ef.PNG)
Since release of BC we have 3 live versions of the game:
1. Burning Crusade Classic
2. World of Warcraft Classic
3. World of Warcraft

With code **`wowclassic`** launcher is opening 1. Burning Crusade Classic - BC Classic realms
With code **`wow`** launcher is opening 3. World of Warcraft - Retail Shadowlands

There is no code option to open 2. World of Warcraft Classic which are Vanilla WoW realms, please add this code so we can use your launcher to open and play Vanilla WoW realms.

**Comment by Dajova** [comment]
Just to add something here: Would be possible to get a option for WotLK Classic in the future as well? Since its coming out soon-ish?

**Comment by Sectimus** [comment]
Now with Hardcore being released I have a reason to distinguish these in my steam launcher from the current classic (WotLK) - I have opened a PR that adds support for "classic era" as this is the codename for the **true** classsic experience. Once approved: this can be activated with the launch parameter "wowclassicera".
If you want to view it in advance there is a [release on my fork](https://github.com/Sectimus/bnetlauncher/releases/tag/v2.23) of this project.

**Comment by Sectimus** [comment]
This is now implemented in v2.23 with the launch parameter of "wowclassicera"

**Comment by Sectimus** [comment]
This is now implemented in [v2.23](https://github.com/dafzor/bnetlauncher/releases/tag/v2.23) with the launch parameter of "wowclassicera"
