### ISSUE TITLE
A way to launch overwatch 2 beta

### ISSUE THREAD

**Issue by juliocoliveira** [dafzor/bnetlauncher#71]
There is any way to launch the beta of overwatch 2?
If i switch the branch/game version on battlenet to Overwatch 2 Tech Beta, close the launcher and launch by this program with the command ow it launches overwatch 1.
I saw that is a gamedb.ini to add custom games but in the parameters i don't see the branch/game version option.

**Comment by lolcatplays** [comment]
```
[ow2]
name=Overwatch 2
client=battlenet
cmd=prob
exe=Overwatch.exe
```

may have to use the experimental build and battlenet2 client to click play automatically

**Comment by juliocoliveira** [comment]
It didn't worked, It showed the game not found window.
Tried battlenet beta, didn't worked either.
![image](https://user-images.githubusercontent.com/6606725/165651493-807e1bf4-29f2-42c3-8f4a-1ab4c80d27b8.png)

**Comment by juliocoliveira** [comment]
I'm using the latest 2.16 version of bnetlauncher. There is a newer version? The experimental version? how i do download it? Or you mean experimental version of battlenet launcher, the beta? Tried beta didn't worked.

**Comment by juliocoliveira** [comment]
I changed the "client=battlenet" to "client=battlenet2" and it worked, Thanks!

**Comment by beeters** [comment]
Oh cool I didn't know that method was a thing. What I did to get it to work is uninstalling OW1
