### ISSUE TITLE
Add support for Diablo Immortal

### ISSUE THREAD

**Issue by PhantomLiberty** [dafzor/bnetlauncher#72]
Please? Would be nice!

Thanks

**Comment by KyleStilkey** [comment]
[diabloi]
name=Diablo Immortal
client=battlenet
cmd=ANBS
exe=DiabloImmortal.exe

Add this to your gamedb.ini to launch Immortal with this for the time being.

**Comment by PhantomLiberty** [comment]
Thanks! Works fine.
