### ISSUE TITLE
Breaks XInput in Overwatch

### ISSUE THREAD

**Issue by beeters** [dafzor/bnetlauncher#74]
Today, when I tried to use this with Overwatch, no controller input would be recognized at all in-game. This wasn't an issue earlier this week. I suspect a new Battle.net Launcher update broke compatibility with this. Could you please release a quick update to fix it? I'm not sure if it's just for Overwatch, if this is the case for every Battle.net game, or if it's just happening for me.

Also, the Battle.net launcher is giving me an error message: "Whoops! Looks like something broke. Give it another shot. More help: BLZBNTAGT00000BC9 Or contact Customer Support if this continues."

**Comment by beeters** [comment]
On further investigation, it seems like any method of running Overwatch or Battle.net through Steam breaks controller input. Also, weirdly enough, even running Battle.net normally sometimes gives me the error message, so I have no idea what to make of that.

**Comment by dafzor** [comment]
bnetlauncher only launches the game in a way that allows the steam overlay to attach.

I've tested overwatch and steam overlay is attaching correctly so bnetlauncher is working correctly, beyond that is between valve and blizzard.

Blizzard may have intentionally broke steam functionality (like destiny 2 did when it was on battle.net). Or it's something valve needs to fix.

**Comment by beeters** [comment]
I hope they didn't intentionally  do that. I've been using bnetlauncher to apply a Steam controller config that overrides the game's massive forced deadzones.

... Configs overall are great but most importantly, Steam's Anti-Deadzone feature won't apply without bnetlauncher's intervention, so that's basically been my use case (for which bnetlauncher has been the only working solution, besides maybe reWASD which I've yet to try).

Knowing that, do you happen to know what could achieve the same effect of overriding or completely removing the game's controller stick deadzones? (I'm honestly not even sure reWASD would do the trick)

**Comment by dafzor** [comment]
I don't have much experience with controllers, I'd recommend searching/asking on [r/SteamController](https://www.reddit.com/r/SteamController/) which is frequented by more knowledgable controller users.

**Comment by beeters** [comment]
I was able to fix it on my own (mostly) with a combination of methods, you can close this now (or I can I think).

Want me to post here how I fixed it? (On the off chance that someone else has the same use case as me for bnetlauncher as well as the same issue and ends up finding this looking for a solution.)

Otherwise it could be a waste of space and detract from what this is for, so I won't post it if you don't want me to.

**Comment by dafzor** [comment]
> Want me to post here how I fixed it?

Up to you, [relevant xkcd](https://xkcd.com/979/).

**Comment by beeters** [comment]
**SOLUTION:**

(This should be my last comment on this Issue)

- Delete your main _Battle.net_ folder if you know where it is
• (Save any custom bnetlauncher settings if needed)

- Go to ``%APPDATA%`` (from the address bar in File Explorer)

- Delete any folders named _Battle.net_ or _Blizzard Entertainment_
• Repeat for ``%PROGRAMDATA%``, ``%APPDATA%``, and ``%TEMP%``, then empty your Recycle Bin

- Reinstall Battle.net (to your main/"C:" drive if possible)
• Sign in (confirm stay signed in) and redownload Overwatch
• Navigate to Overwatch's _Game Settings_ (in Battle.net)
• Reset in-game settings (this will not reset your per-hero options) and confirm changes before closing the window
• Repair the game

- Uninstall all Razer apps except for _Razer Controller Setup For Xbox_
• Later, when the issue is fixed, reinstall needed software 1 at a time to narrow down any leftover culprits

- Disable all Windows 10 Game Mode functions (Windows Start, Settings, Gaming, disable all tabs/items)

- Reinstall bnetlauncher to your Battle.net folder from earlier
• Delete the compressed folder after extracting. (I don't think this is necessary, but I did it, so I'm putting it here.)

- In Steam, add bnetlauncher as a Non-Steam Game, right click on it, and navigate to _Properties..._

- Navigate to _Target_ and paste the following, including the quotation marks: ``"C:\Program Files (x86)\Battle.net\bnetlauncher.exe" ow``

- Navigate to _Start In_ and paste the following: ``C:\Program Files (x86)\Battle.net``

- Navigate to _Launch Options_ and paste the following: ``-t -n -l -high -USEALLAVAILABLECORES -dev -preload -d3d9ex -64bit``

- OPTIONAL: Add more launch options to help performance on low-end/mid-end PCs, especially if Big Picture Mode is necessary later:
• ``-cpuCount=``[# of CPU cores]
• ``-threads=``[2(# of cores)]
• ``-exThreads=``[2(# of cores) - 1]
-- Must be ``0``, ``1``, ``3``, ``5``, or ``7``
• ``-maxMem=``[1000(# GB RAM)]
-- Must be ``4000``, ``8000``, ``12000``, or ``16000``; if necessary, round up or down to the next possible value, then test from there
-- No commas, e.g., ``16000`` is viable, but not ``16,000``
• ``-maxVram=``[1,024(# GB VRAM) - 512]
-- No commas, e.g., not ``7,680``
• ``-heapsize=``[524,228(# GB RAM)]
-- No commas, e.g., not ``8,387,648``

- OPTIONAL: These 3 launch options (especially the first 2) could actually cause performance issues in newer hardware/OSs/games or higher settings, but they could help performance in some cases. Experiment with them:
• ``+r_rootlod 2``
• ``+mat_hdr_level 0``
• ``+mat_trilinear 0``

- OPTIONAL (not recommended): This last launch option will help if you encounter a lot of stuttering, but only if you have >/= 8 GB VRAM:
• ``-notexturestreaming``
-- If you care about visuals, max out settings you suspect might affect the distance that textures stream out, e.g., _Graphics Quality_ and _Texture Quality_.

- Shut down your PC for >/= 60 seconds, then launch your new non-Steam game shortcut
• (It might freeze/crash the first time because you reset your in-game audio/video settings. ``Ctrl+alt+Delete`` then sign out if needed, then try again)

________________________________

**IF THE ISSUE PERSISTS:**

- Run an extended power cycle:
• Turn off all related devices, including your modem, router, and PC. Wait 30 minutes
• Turn on your modem. Wait 5 minutes
• Turn on any other network devices. Wait 2 minutes
• Turn on your PC and try the game again

- Change your DNS server to a different/free public one instead of your ISP's:
• See https://www.lifewire.com/free-and-public-dns-servers-2626062 for a tutorial on how to do so and a list of free DNS servers
• I recommend _Cloudflare_

- Turn off any non-Windows firewall software. Then, disable the following routing/security features:
• ``QoS``
• ``SIP ALG``
• ``RoG`` (ASUS Routers only)
• Security firewalls (some ISP-provided modems)

- Make sure your profile on your PC is an administrator profile, then double-check your firewall/router settings

- Open Steam in Big Picture Mode and make sure your controller is connected and recognized by Steam:
• When you open Steam with your controller connected, or at least when you connect your controller while Steam is open, it should display a message saying "Imported configs from [your controller's set name]"
• In Big Picture Mode, you can use your controller to navigate through Steam. If you don't get any message, use this feature to test if Steam registers input from your controller

- Navigate to your bnetlauncher non-Steam game shortcut (optionally renamed to "Overwatch") and try playing it
• (Once again: It might freeze/crash the first time because you reset your in-game audio/video settings. ``Ctrl+alt+Delete`` then sign out if needed, then try again)

- After all these steps, the issue should be fixed. If the issue still persists, in a last-ditch effort, try contacting Blizzard Support: https://us.battle.net/support/en/help/

- If all else fails, create a new Issue on bnetlauncher's GitHub page and hope for the best. Godspeed
