### ISSUE TITLE
Not Launching Overwatch 2

### ISSUE THREAD

**Issue by juliocoliveira** [dafzor/bnetlauncher#76]
![image](https://user-images.githubusercontent.com/6606725/193934548-e5d3a431-fd86-4ffd-82d7-664c73d5cbc2.png)
Not launching Overwatch 2 correctly, It opens the process but it keep stuck with low cpu and ram usage, The window does not open.
db:
[ow2]
name=Overwatch 2
client=battlenet2
cmd=pro
exe=Overwatch.exe

**Comment by dafzor** [comment]
Just tested and it seems to be working normally without changing anything. Was yours a new install or a converted overwatch 1 install?

**Comment by juliocoliveira** [comment]
To me it launches but only opens after 1 minute, If I launch by the battle.net it opens in the same time.
Converted overwatch 1.
Tried removing the db and launching by ow param, but it does the same thing.

**Comment by juliocoliveira** [comment]
Did a repair too, but the same issue still happen

**Comment by dafzor** [comment]
What's your battle.net launcher version?

**Comment by juliocoliveira** [comment]
![image](https://user-images.githubusercontent.com/6606725/193949099-8b0c6eec-5bb0-4131-b5ba-48be688024d5.png)

**Comment by dafzor** [comment]
Still can't reproduce, follow the [troubleshoot steps](https://github.com/dafzor/bnetlauncher#troubleshooting) and post the log and i'll try to take a look.

**Comment by juliocoliveira** [comment]
20:38:22.4016|20700|Program.Main:133|INFO|Starting bnetlauncher v2.17.8203.29406
20:38:22.4046|20700|Program.LogSystemInfo:733|INFO|Getting System details:
20:38:22.4046|20700|Program.LogSystemInfo:737|INFO|ENV: Microsoft Windows NT 10.0.22621.0 (4.0.30319.42000), 64bit
20:38:22.4813|20700|Program.LogSystemInfo:803|INFO|OS: Microsoft Windows 11 Pro (10.0.22621, 64-bit, 1033)
20:38:22.4813|20700|Program.LogSystemInfo:804|INFO|CPU: AMD Ryzen 7 5800X 8-Core Processor             , RAM: 32768MB
20:38:22.4813|20700|Program.LogSystemInfo:805|INFO|GPU: NVIDIA GeForce RTX 3060 Ti (31.0.15.1748, 4095MB)
20:38:22.4813|20700|Program.LogSystemInfo:806|INFO|HDD: SAMSUNG HD103SJ, Samsung M3 Portable USB Device, KINGSTON SA400S37120G, Force MP600
20:38:22.4898|20700|Program.LoadGameList:594|INFO|Loading gamedb files.
20:38:22.4993|20700|Program.LoadGameList:606|INFO|Loaded 'V:\Battle.net\gamesdb.ini' with '26' games.
20:38:22.5003|20700|Program.LoadGameList:615|INFO|Loaded internal gamedb with '27' games.
20:38:22.5003|20700|Program.LoadGameList:632|INFO|Known games: '28'.
20:38:22.5003|20700|Program.Main:228|INFO|Given parameter 'ow2'.
20:38:22.5013|20700|Program.Main:264|INFO|Using 'battlenet2' client.
20:38:22.5013|20700|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
20:38:22.5013|20700|Program.Main:280|INFO|Checking for other bnetlauncher processes using same client
20:38:22.5013|20700|Program.Main:288|INFO|No other bnetlauncher detected
20:38:22.5303|20700|BnetClient.Start:124|INFO|Starting 'battlenet2' client.
20:38:22.5303|20700|BnetClient.Start:133|INFO|Starting the client trough task.
20:38:22.5303|20700|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
20:38:22.5609|20700|Tasker.Exists:125|INFO|Found task for battlenet2.
20:38:22.5629|20700|Tasker.Run:92|INFO|Starting battlenet2 task.
20:38:24.5863|20700|BnetClient.WaitUntilReady:180|INFO|Waiting for battle.net client to be ready.
20:38:28.9344|20700|BnetClient.WaitUntilReady:219|INFO|Client fully running with pid:'24508'
20:38:28.9344|20700|Program.Main:350|INFO|Issuing game launch command 'pro' at '08:38:28.9344'
20:38:28.9354|20700|BnetClient2.Launch:55|INFO|Looking for installPath for 'pro'
20:38:28.9364|20700|BnetClient.GetProductInstallPath:242|INFO|Opening 'C:\ProgramData\battle.net\Agent\product.db'
20:38:29.0366|20700|BnetClient.GetProductInstallPath:252|INFO|Found install path 'V:/Battle.net/Overwatch'.
20:38:29.0366|20700|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
20:38:29.3351|20700|BnetClient2.Launch:86|INFO|Found windows for battle.net client.
20:38:29.8459|20700|WinApi.CaptureProcessMainWindow:187|INFO|Found window at position: 15,160.
20:38:29.9060|20700|WinApi.FindColorInProcessMainWindow:220|WARN|Couldn't find color in Window.
20:38:30.0192|20700|WinApi.CaptureProcessMainWindow:187|INFO|Found window at position: 15,160.
20:38:30.0623|20700|WinApi.FindColorInProcessMainWindow:214|INFO|Found color Color [A=255, R=0, G=116, B=224] in Window at 43,920
20:38:30.0623|20700|BnetClient2.Launch:111|INFO|Sending Mouse click at window
20:38:30.1124|20700|Processes.GetProcessByNameAfterDate:159|INFO|Searching for process 'Overwatch.exe' for '15' seconds.
20:38:30.4284|20700|Processes.GetProcessByNameAfterDate:168|INFO|Found game process started at '08:38:30.3704' with pid:'21688'
20:38:30.4294|20700|Processes.GetProcessStartInfoById:86|INFO|Attempt 1 to find start parameters
20:38:30.5637|20700|Processes.GetProcessStartInfoById:124|INFO|Filename:'V:\Battle.net\Overwatch\_retail_\Overwatch.exe'.
20:38:30.5637|20700|Processes.GetProcessStartInfoById:125|INFO|Arguments:' -uid prometheus'.
20:38:30.5637|20700|Program.Main:428|INFO|Closing game process and starting it under bnetlauncher
20:38:30.6268|20700|Program.CloseClientIfLast:672|INFO|Closing client 'battlenet2'.
20:38:31.3124|20700|Program.Main:508|INFO|All operations successful, exiting

**Comment by dafzor** [comment]
Realised you're using your custom `ow2` profile instead of the built in `ow`. I was just using built in `ow` profile to launch Overwatch 2 (still the same game).

That said from your log everything seems successful however the reported path of the game is "odd", is your game really installed in `V:\Battle.net\Overwatch_retail_\Overwatch.exe`?

For comparison my game exe is in `C:\Games\Overwatch\_retail_\Overwatch.exe`.

**Comment by juliocoliveira** [comment]
Mine have a ``` _retail_``` folder too.

**Comment by juliocoliveira** [comment]
![image](https://user-images.githubusercontent.com/6606725/193951231-82de8e9f-ef48-4d4a-a262-19f7f4a376d9.png)

**Comment by dafzor** [comment]
But the log line is reporting a `Overwwatch_retail_` folder:

```
20:38:30.5637|20700|Processes.GetProcessStartInfoById:124|INFO|Filename:'V:\Battle.net\Overwatch_retail_\Overwatch.exe'.
```
Instead of the correct path, it seems battlenet2 path discovery might be broken, but that said it's not required to launch Overwatch, if you use `ow` it should work normally.

Please try using the built in `ow` to launch the game

**Comment by juliocoliveira** [comment]
Already did as i said before, With ow2 custom or built-in ow the result is the same, it takes over a minute to open the window.
```
21:08:58.9283|23464|Program.Main:133|INFO|Starting bnetlauncher v2.17.8203.29406
21:08:58.9308|23464|Program.LogSystemInfo:733|INFO|Getting System details:
21:08:58.9308|23464|Program.LogSystemInfo:737|INFO|ENV: Microsoft Windows NT 10.0.22621.0 (4.0.30319.42000), 64bit
21:08:59.0075|23464|Program.LogSystemInfo:803|INFO|OS: Microsoft Windows 11 Pro (10.0.22621, 64-bit, 1033)
21:08:59.0075|23464|Program.LogSystemInfo:804|INFO|CPU: AMD Ryzen 7 5800X 8-Core Processor             , RAM: 32768MB
21:08:59.0085|23464|Program.LogSystemInfo:805|INFO|GPU: NVIDIA GeForce RTX 3060 Ti (31.0.15.1748, 4095MB)
21:08:59.0085|23464|Program.LogSystemInfo:806|INFO|HDD: SAMSUNG HD103SJ, Samsung M3 Portable USB Device, KINGSTON SA400S37120G, Force MP600
21:08:59.0160|23464|Program.LoadGameList:594|INFO|Loading gamedb files.
21:08:59.0260|23464|Program.LoadGameList:615|INFO|Loaded internal gamedb with '27' games.
21:08:59.0260|23464|Program.LoadGameList:632|INFO|Known games: '27'.
21:08:59.0260|23464|Program.Main:228|INFO|Given parameter 'ow'.
21:08:59.0260|23464|Program.Main:264|INFO|Using 'battlenet' client.
21:08:59.0260|23464|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
21:08:59.0270|23464|Program.Main:280|INFO|Checking for other bnetlauncher processes using same client
21:08:59.0270|23464|Program.Main:288|INFO|No other bnetlauncher detected
21:08:59.0651|23464|BnetClient.Start:124|INFO|Starting 'battlenet' client.
21:08:59.0651|23464|BnetClient.Start:133|INFO|Starting the client trough task.
21:08:59.0661|23464|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
21:08:59.0966|23464|Tasker.Exists:125|INFO|Found task for battlenet.
21:08:59.0982|23464|Tasker.Run:92|INFO|Starting battlenet task.
21:09:01.1206|23464|BnetClient.WaitUntilReady:180|INFO|Waiting for battle.net client to be ready.
21:09:05.5935|23464|BnetClient.WaitUntilReady:219|INFO|Client fully running with pid:'5840'
21:09:05.5935|23464|Program.Main:350|INFO|Issuing game launch command 'Pro' at '09:09:05.5935'
21:09:05.5935|23464|BnetClient.InstallPath:86|INFO|Client InstallPath:'V:\Battle.net'.
21:09:05.6781|23464|Processes.GetProcessByNameAfterDate:159|INFO|Searching for process 'Overwatch.exe' for '15' seconds.
21:09:06.3258|23464|Processes.GetProcessByNameAfterDate:168|INFO|Found game process started at '09:09:06.2769' with pid:'7988'
21:09:06.3268|23464|Processes.GetProcessStartInfoById:86|INFO|Attempt 1 to find start parameters
21:09:06.4585|23464|Processes.GetProcessStartInfoById:124|INFO|Filename:'V:\Battle.net\Overwatch\_retail_\Overwatch.exe'.
21:09:06.4585|23464|Processes.GetProcessStartInfoById:125|INFO|Arguments:' -uid prometheus'.
21:09:06.4585|23464|Program.Main:428|INFO|Closing game process and starting it under bnetlauncher
21:09:06.5126|23464|Program.CloseClientIfLast:672|INFO|Closing client 'battlenet'.
21:09:07.2258|23464|Program.Main:508|INFO|All operations successful, exiting
```

**Comment by dafzor** [comment]
On the `ow` log I'm not seeing anything wrong and matches the log when running my own machine:

```
01:29:14.8470|17680|Program.Main:133|INFO|Starting bnetlauncher v2.17.8203.29406
01:29:14.8490|17680|Program.LogSystemInfo:733|INFO|Getting System details:
01:29:14.8500|17680|Program.LogSystemInfo:737|INFO|ENV: Microsoft Windows NT 10.0.19044.0 (4.0.30319.42000), 64bit
01:29:14.8981|17680|Program.LogSystemInfo:803|INFO|OS: Microsoft Windows 10 Pro (10.0.19044, 64-bit, 1033)
01:29:14.8991|17680|Program.LogSystemInfo:804|INFO|CPU: AMD Ryzen 9 5950X 16-Core Processor            , RAM: 32768MB
01:29:14.8991|17680|Program.LogSystemInfo:805|INFO|GPU: AMD Radeon RX 5700 XT (30.0.15021.11005, 4095MB)
01:29:14.8991|17680|Program.LogSystemInfo:806|INFO|HDD: WDC WD40EFRX-68N32N0, Samsung SSD 980 PRO 2TB, CT2000MX500SSD1, Samsung SSD 840 EVO 250GB, WDC WD40EFRX-68N32N0, Samsung SSD 970 EVO 500GB, SAMSUNG HD103SJ
01:29:14.9081|17680|Program.LoadGameList:594|INFO|Loading gamedb files.
01:29:14.9161|17680|Program.LoadGameList:606|INFO|Loaded 'C:\Users\daf\AppData\Local\madalien.com\bnetlauncher\gamedb.ini' with '1' games.
01:29:14.9171|17680|Program.LoadGameList:615|INFO|Loaded internal gamedb with '27' games.
01:29:14.9171|17680|Program.LoadGameList:632|INFO|Known games: '28'.
01:29:14.9171|17680|Program.Main:228|INFO|Given parameter 'ow'.
01:29:14.9171|17680|Program.Main:264|INFO|Using 'battlenet' client.
01:29:14.9181|17680|BnetClient.InstallPath:86|INFO|Client InstallPath:'C:\Program Files (x86)\Battle.net'.
01:29:14.9181|17680|Program.Main:280|INFO|Checking for other bnetlauncher processes using same client
01:29:14.9181|17680|Program.Main:288|INFO|No other bnetlauncher detected
01:29:14.9411|17680|BnetClient.Start:124|INFO|Starting 'battlenet' client.
01:29:14.9411|17680|BnetClient.Start:133|INFO|Starting the client trough task.
01:29:14.9411|17680|BnetClient.InstallPath:86|INFO|Client InstallPath:'C:\Program Files (x86)\Battle.net'.
01:29:14.9672|17680|Tasker.Exists:125|INFO|Found task for battlenet.
01:29:14.9682|17680|Tasker.Run:92|INFO|Starting battlenet task.
01:29:16.9828|17680|BnetClient.WaitUntilReady:180|INFO|Waiting for battle.net client to be ready.
01:29:21.2098|17680|BnetClient.WaitUntilReady:219|INFO|Client fully running with pid:'12988'
01:29:21.2098|17680|Program.Main:350|INFO|Issuing game launch command 'Pro' at '01:29:21.2098'
01:29:21.2108|17680|BnetClient.InstallPath:86|INFO|Client InstallPath:'C:\Program Files (x86)\Battle.net'.
01:29:21.2628|17680|Processes.GetProcessByNameAfterDate:159|INFO|Searching for process 'Overwatch.exe' for '15' seconds.
01:29:21.9435|17680|Processes.GetProcessByNameAfterDate:168|INFO|Found game process started at '01:29:21.9222' with pid:'20320'
01:29:21.9445|17680|Processes.GetProcessStartInfoById:86|INFO|Attempt 1 to find start parameters
01:29:22.0756|17680|Processes.GetProcessStartInfoById:124|INFO|Filename:'C:\Games\Overwatch\_retail_\Overwatch.exe'.
01:29:22.0756|17680|Processes.GetProcessStartInfoById:125|INFO|Arguments:' -uid prometheus'.
01:29:22.0756|17680|Program.Main:428|INFO|Closing game process and starting it under bnetlauncher
01:29:22.1106|17680|Program.CloseClientIfLast:672|INFO|Closing client 'battlenet'.
01:29:22.4239|17680|Program.Main:508|INFO|All operations successful, exiting
```

I'll need a 3rd party to confirm it working or broken before I know which of our systems is the odd one out.

**Comment by magic-bit-works** [comment]
Below is what I was able to launch from Steam.
I hope this is helpful.

## The directory structure is as follows.
```
bnetlauncher
 |- bnetlauncher.exe
 |- gamesdb.ini
```
## The settings are as follows.
#### 1. add gamesdb.ini
```
[ow2]
name=Overwatch
client=battlenet
cmd=Pro
exe=%\Overwatch.exe
```
#### 2. Add a Non-Steam Game
```
TARGET
"G:\Steam\bnetlauncher\bnetlauncher.exe"

START IN
"G:\Battle.net\Overwatch\"

LAUNCH OPTIONS
ow2
```
#### 3. Play OverWatch2 from Steam.
## There is a problem.
you cannot exit from Steam this way.
If you exit from OverWatch, Battle.net window will remain.

**Comment by juliocoliveira** [comment]
With your command my overwatch 2 don't take over a minute to start, it starts right away.
About battle.net auto exit you can force it on settings:
![image](https://user-images.githubusercontent.com/6606725/195153571-4d922ca0-1020-438b-9333-f18950dd4deb.png)

**Comment by juliocoliveira** [comment]
The problem that i found with that custom db command is that steam overlay does not work at all.

**Comment by dafzor** [comment]
You shouldn't need to add a new command, the existing `ow` should still work as expected.

Also the `\` in `%\Overwatch.exe` is not a valid character for an exe name.

**Comment by magic-bit-works** [comment]
> juliocoliveira

Thank you:)

> you cannot exit from Steam this way.
> If you exit from OverWatch, Battle.net window will remain.

Battle.net App Setting
"Restore BAttle.net window when the game ends" on disable.
able to resolve the issue.

**Comment by magic-bit-works** [comment]
> dafzor

Thanks for the reply.
and Thanks for developing a great APP:)

> Also the `\` in `%\Overwatch.exe` is not a valid character for an exe name.

Changed `%\Overwatch.exe` to `%\/Overwatch.exe`.
I am could not be deciphered the file "bnetlauncher/Program.cs".

> You shouldn't need to add a new command, the existing ow should still work as expected.

Sorry.
I could not start it in my environment.

Perhaps.
I assume it is because the APP path has been changed as follows.

OverWatch 1
```
G:\Battle.net\Overwatch
Overwatch.exe
```

OverWatch 2(overwatch 1 upgrade to overwatch 2)
```
G:\Battle.net\Overwatch\_retail_
Overwatch.exe
```

My method is not official, but
I have solved the problem for now.
Thank you.

**Comment by dafzor** [comment]
> Changed `%\Overwatch.exe` to `%\/Overwatch.exe`.

The exe name should not contain directory separator characters, it's only matched with the name. It's using [WQL](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wql-sql-for-wmi) to query the [WMI](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page).

You can run a similar query to the one bnetlauncher uses in Windows Powershell
```powershell
$exe= 'Overwatch.exe'
Get-WmiObject -Query "SELECT Name, ProcessId, CreationDate FROM Win32_Process WHERE Name LIKE '$($exe)%'"
```

Glad you got things working for you.

**Comment by juliocoliveira** [comment]
Why you close it? I still having issue with the launcher....

**Comment by magic-bit-works** [comment]
> Why you close it? I still having issue with the launcher....

Sorry.
It was not closing.
It was shrinking the launcher after the game.

Because I am using "Steam" in Big Picture Mode.
I am using a controller only.

After the game
"Battle.net" window cannot be operated when it is in the foreground.

**Comment by juliocoliveira** [comment]
I mean the issue, @dafzor closed it.
For me is not fixed.
If i use built-in ow command it takes over a minute to open the overwatch 2 window, But everything works fine.
If i use your @samurai-archive db entry it launches right away after clicking on Launch/ Play, but the Overlay does not work.
If i launch using standard battle.net launcher from desktop it works fine but not steam overlay, If i launch from steam from battle.net command Battle.net.exe --exec="launch Pro" it does not auto launch, takes over a minute to open the window but the overlay works.

**Comment by dafzor** [comment]
> Why you close it? I still having issue with the launcher....

Because there wasn't anything more to be done on my side. That said I've reopened so it's visible to other users.

**Comment by juliocoliveira** [comment]
@dafzor ok, thanks. Do you have any idea why with @samurai-archive's db entry it launches right away but with the built-in ow one it takes over a minute to launch. Have any guess?

**Comment by dafzor** [comment]
> @dafzor ok, thanks. Do you have any idea why with @samurai-archive's db entry it launches right away but with the built-in ow one it takes over a minute to launch. Have any guess?

The only difference from the [built-in ow entry](https://github.com/dafzor/bnetlauncher/blob/master/bnetlauncher/Resources/gamesdb.ini#L61) and @samurai-archive one is the invalid exe name, thus i'd expect it to work without the overlay as it can't find the game running (exe name will never match).

If with `ow` it take 1m i can only guess it's some interaction of overwatch and steam or even some anti-virus software.

you can use `windows key + R` to run `bnetlauncher ow` on it's own without steam and see if that also takes a long time. If it doesn't then the issue might be steam overlay itself.

**Comment by juliocoliveira** [comment]
Yes is some issue with steam, I launched from Run as you said and it launched in 6 seconds after auto clicked on Play/Launch.
Its not AV because i disabled all the modules from my Kaspersky Plus and it still took over a minute to open.
That said any clue of how to fix it? Maybe its a Windows 11 22h2 issue with steam i don't know.

**Comment by dafzor** [comment]
I use steam beta and windows 10, so you can try switching to the steam beta if you're not using it.

Other then that no other suggestion.

**Comment by juliocoliveira** [comment]
Bummer, steam beta didn't fixed, Probably its a Steam Overlay in Windows 11 22h2 issue for Overwatch 2 specifically, Other non steam games opens normal, and tested with StarCraft II and it opens normally too.

Its not the worst thing in the World waiting 76 seconds to play a game, its just really annoying.

**Comment by juliocoliveira** [comment]
Tried everything, run as Windows 8 compatibility, Run as Administrator, nothing fixes. As administrator the overlay does not work at all.

I just want know if this is normal for all Windows 11 users, or only me.

**Comment by juliocoliveira** [comment]
I tested on Windows 10, and it runs normally, So its a Steam Overlay issue on Overwatch 2 for Windows 11.

**Comment by juliocoliveira** [comment]
Its fixed, Today was released an update that fixed this issue! Thanks for the support!
