### ISSUE TITLE
Add support for COD Modern Warfare 2 (CODhq)

### ISSUE THREAD

**Issue by JonJaded** [dafzor/bnetlauncher#77]
Please and thank you!

**Comment by JonJaded** [comment]
Added a link containing relevant info as requested in #45 

https://imgur.com/a/9NCLW1m

I also wanted to show that there are multiple games within this one game, a launcher for singleplayer, multiplayer, and later down the line when warzone releases, there will probably another one for it too.

But the relevant executable is the one at the end of the album, its the launcher home for these series of games.

**Comment by d3rt0xx** [comment]
Just add this to your gamesdb.ini (%localappdata%\madalien.com\bnetlauncher\)

[codmw2]
name=Call of Duty: MWII | WZ2.0
client=battlenet
cmd=AUKS
exe=cod.exe
options=waitforexit

**Comment by dafzor** [comment]
Resolved in #78

**Comment by JonJaded** [comment]
Appreciate your consistent support. Thank you.

**Comment by dafzor** [comment]
> Appreciate your consistent support. Thank you.

Direct your thanks to @d3rt0xx who actually added support.
