### ISSUE TITLE
StarCraft Remastered Support

### ISSUE THREAD

**Issue by RobFreiburger** [dafzor/bnetlauncher#8]
Howdy,

With some testing on my own, the battlenet://SCR argument launches Battle.net App to the StarCraft Remastered screen. However I don't own the game, so I can't confirm this works with the actual game.

Thanks for the tool and your support.

**Comment by dafzor** [comment]
Thanks for the info, I'll update the docs to include it.
In the meantime using "SCR" should work just fine since bnetlauncher will always try to use what's it's given.

**Comment by dafzor** [comment]
Version 1.13 released that has the new alias.
Do you happen to know how people are finding out the battlenet URI?

**Comment by RobFreiburger** [comment]
Frankly I just guessed. It seemed reasonable to try SCR given the patterns of the other games' URIs.

**Comment by dafzor** [comment]
I see, once again thanks for the help.
