### ISSUE TITLE
Warcraft I Remastered & Warcraft II Remastered

### ISSUE THREAD

**Issue by Aqvilinus** [dafzor/bnetlauncher#95]
Hi. Could you please add these two?

**Comment by Aqvilinus** [comment]
I added them manually through `%localappdata%\madalien.com\bnetlauncher\gamedb.ini`, but it would be great to have an out-of-the-box solution.

Here's my `gamedb.ini` for anyone interested—a tested and working version:

```
[w1r]
name=Warcraft I: Remastered
client=battlenet2
cmd=w1r
exe=Warcraft.exe

[w2r]
name=Warcraft II: Remastered
client=battlenet2
cmd=w2r
exe=Warcraft II.exe
```

Use the `w1r` and `w2r` command-line arguments to launch the game through BnetLauncher and Steam.

**Comment by Aqvilinus** [comment]
P.S. To find internal product codes (used in the cmd field above), the fastest method isn't combing through logs as described in the project documentation. Instead, launch the game through Battle.net, then alt-tab to the desktop and open a PowerShell console. Enter the following command (I use Warcraft II Remastered in my example):

`Get-WmiObject Win32_Process -Filter "name = 'Warcraft II.exe'" | Select-Object CommandLine`

You'll get an output like this:

```
CommandLine
-----------
"E:\Games\Blizzard Games\Warcraft II Remastered\x86\Warcraft II.exe" -uid w2r
```

The value of the `-uid` parameter is the code you need. This method works with any Blizzard game — just use the correct .exe name in the command.

**Comment by ShizCalev** [comment]
There's a PR that's almost a year old to add support for a game, I think the dev has stopped maintaining this fully at this point.

I've made my own version which you can find here that is more or less a drop-in replacement (you just have to update the .exe name for your shortcuts, otherwise all the commands are the same.)

https://github.com/ShizCalev/Battlenet-Launcher

**Comment by Aqvilinus** [comment]
Hi @ShizCalev, I tested your tool out of curiosity. Unfortunately, it doesn’t work if Battle.net is installed in a non-default folder. My installation is at E:\Games\Battle.net.

**Comment by dafzor** [comment]
> There's a PR that's almost a year old to add support for a game, I think the dev has stopped maintaining this fully at this point.

Pretty much, at this point I don't even use Windows as my main OS making it even harder to validate changes.

I tried finding someone who still had some interest to maintain the project but didn't work out.

Still, took some time to do a [pre-release](https://github.com/dafzor/bnetlauncher/releases/tag/v2.24) with all the pending changes and zero testing, hope it helps @Aqvilinus .
